name = "DiffMatic"
uuid = "ec55c3ff-feb8-4051-a6a4-2e9f18c613fc"
authors = ["Jimmy Envall <jimmyenvall@gmail.com>"]
version = "0.0.1-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.10"
LinearAlgebra = "1.10"
